import { useEffect, useState } from "react";
import { Save } from "lucide-react";
import { Input } from "@/components/ui/Input";
import { Switch } from "@/components/ui/Switch";
import { Slider } from "@/components/ui/Slider";
import { Select } from "@/components/ui/Select";
import { Button } from "@/components/ui/Button";
import { cn } from "@/lib/cn";
import { useAppData } from "@/context/AppData";
import type { AppSettings } from "@/lib/api";
const SECTIONS=["General","Startup","Tab Monitor","Appearance","Notifications"] as const; type Section=(typeof SECTIONS)[number];
export function SettingsPage(){
 const {settings,saveSettings}=useAppData(); const [section,setSection]=useState<Section>("General"); const [form,setForm]=useState<AppSettings>(settings); const [saving,setSaving]=useState(false); useEffect(()=>setForm(settings),[settings]);
 const patch=<K extends keyof AppSettings>(k:K,v:AppSettings[K])=>setForm(p=>({...p,[k]:v})); async function save(){setSaving(true);await saveSettings(form);setSaving(false)}
 return <div className="mx-auto flex max-w-4xl gap-10 px-8 py-8"><nav className="w-40 shrink-0">{SECTIONS.map(s=><button key={s} onClick={()=>setSection(s)} className={cn("block w-full rounded-md px-2.5 py-1.5 text-left text-[13px] transition-colors",section===s?"bg-accent/10 text-text-primary":"text-text-secondary hover:bg-white/5 hover:text-text-primary")}>{s}</button>)}</nav><div className="flex-1"><div className="mb-5 flex items-center justify-between"><h1 className="text-lg font-semibold tracking-tight text-text-primary">{section}</h1><Button variant="primary" size="sm" onClick={()=>void save()} disabled={saving}><Save size={13}/>{saving?"Saving…":"Save changes"}</Button></div>
 {section==="General"&&<div className="flex flex-col gap-5"><Input label="Workspace name" value={form.workspaceName} onChange={e=>patch("workspaceName",e.target.value)}/><Input label="Firefox binary path" value={form.firefoxBinary} onChange={e=>patch("firefoxBinary",e.target.value)}/><Select label="Default browser engine" value="firefox" onChange={()=>{}} options={[{value:"firefox",label:"Firefox"}]}/></div>}
 {section==="Startup"&&<div className="flex flex-col gap-5"><div className="rounded-lg border border-border bg-surface px-4 py-3.5"><Switch checked={form.launchOnLogin} onCheckedChange={v=>patch("launchOnLogin",v)} label="Launch Brainbox on system login" description="Starts the app in the background when you sign in"/></div><div className="rounded-lg border border-border bg-surface px-4 py-3.5"><Switch checked={form.launchAllAuto} onCheckedChange={v=>patch("launchAllAuto",v)} label="Launch all profiles automatically" description="Opens every profile marked enable on startup"/></div><div className="rounded-lg border border-border bg-surface px-4 py-3.5"><label className="mb-2 block text-[13px] text-text-primary">Startup delay between profiles</label><Slider value={form.startupDelay} onChange={v=>patch("startupDelay",v)}/></div><Input label="Default website" value={form.defaultSite} onChange={e=>patch("defaultSite",e.target.value)}/></div>}
 {section==="Tab Monitor"&&<div className="flex flex-col gap-5"><div className="rounded-lg border border-border bg-surface px-4 py-3.5"><Switch checked={form.refreshEnabled} onCheckedChange={v=>patch("refreshEnabled",v)} label="Automatically refresh opened tabs" description="Brainbox monitors tabs opened by each managed Firefox profile."/></div><div className="grid grid-cols-2 gap-4"><Input label="Minimum interval (minutes)" type="number" min={5} value={String(form.refreshMinMinutes)} onChange={e=>{const v=Math.max(5,Number(e.target.value)||5);setForm(p=>({...p,refreshMinMinutes:v,refreshMaxMinutes:Math.max(v,p.refreshMaxMinutes)}))}}/><Input label="Maximum interval (minutes)" type="number" min={5} value={String(form.refreshMaxMinutes)} onChange={e=>patch("refreshMaxMinutes",Math.max(Math.max(5,form.refreshMinMinutes),Number(e.target.value)||5))}/></div><p className="text-[12px] text-text-tertiary">The minimum is locked at 5 minutes. Each refresh is scheduled randomly between the minimum and maximum.</p></div>}
 {section==="Appearance"&&<div className="flex flex-col gap-5"><Select label="Theme" value={form.theme} onChange={v=>patch("theme",v as AppSettings["theme"])} options={[{value:"dark",label:"Dark (default)"},{value:"darker",label:"Darker"}]}/><p className="text-[12px] text-text-tertiary">Brainbox is designed dark first.</p></div>}
 {section==="Notifications"&&<div className="flex flex-col gap-3"><div className="rounded-lg border border-border bg-surface px-4 py-3.5"><Switch checked={form.notifyProxyFail} onCheckedChange={v=>patch("notifyProxyFail",v)} label="Notify on proxy failure" description="Get a system notification when a proxy check fails"/></div><div className="rounded-lg border border-border bg-surface px-4 py-3.5"><Switch checked={form.notifyLaunch} onCheckedChange={v=>patch("notifyLaunch",v)} label="Notify on profile launch" description="Get a system notification each time a profile starts"/></div></div>}
 </div></div>
}
